version: '3'

networks:
  category:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-server
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
    networks:
      - category

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - category

  redis:
    image: library/redis:latest
    container_name: redis-master
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis:/redis/data
    ports:
      - "6379:6379"
    networks:
      - category

  redis-admin:
    image: erikdubbelboer/phpredisadmin
    container_name: redis-admin
    depends_on:
      - redis
    environment:
      - REDIS_1_HOST=redis-master
      - REDIS_1_AUTH=${REDIS_PASSWORD}
      - REDIS_1_PORT=6379
      - ADMIN_USER=root
      - ADMIN_PASS=${REDIS_PASSWORD}
    volumes:
      - ./redis:/redis/data
    ports:
      - "8082:80"
    networks:
      - category
